name: venv_scrapy_amazon
channels:
  - defaults
dependencies:
  - python=3.12
  - ipykernel
  - conda-forge::scrapy
  # - conda-forge::pymongo
  - pandas
  - anaconda::psycopg2
  - conda-forge::asyncpg
  - conda-forge::python-dotenv
  - pip
  - pip:
    - scrapy-user-agents